name: Build Plugin

on:
  push:
    branches: [ "main" ]   # or "master" if that's your branch
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Clear Maven cache for jar plugin
      run: rm -rf ~/.m2/repository/org/apache/maven/plugins/maven-jar-plugin
    
    - name: Build with Maven
      run: mvn clean package

    - name: Upload JAR
      uses: actions/upload-artifact@v4
      with:
        name: plugin-jar
        path: target/*.jar
